FROM centos:centos7.2.1511

RUN yum install -y epel-release unzip
RUN yum install -y nginx php php-fpm

RUN sed -i 's/^;cgi.fix_pathinfo=1$/cgi.fix_pathinfo=0/' /etc/php.ini
RUN sed -i 's/^listen *=.*$/listen = \/var\/run\/php-fpm\/php-fpm.sock/' /etc/php-fpm.d/www.conf
RUN sed -i 's/^;listen.owner *=.*$/listen.owner = nobody/' /etc/php-fpm.d/www.conf
RUN sed -i 's/^;listen.group *=.*$/listen.group = nobody/' /etc/php-fpm.d/www.conf
RUN sed -i 's/^user *=.*$/user = nginx/' /etc/php-fpm.d/www.conf
RUN sed -i 's/^group *=.*$/group = nginx/' /etc/php-fpm.d/www.conf

COPY nginx/config/nginx.conf /etc/nginx/nginx.conf
COPY 269_flatfile_login.zip /269_flatfile_login.zip
COPY nginx/base_files /base_files
COPY run.sh /run.sh
RUN chmod +x /run.sh

RUN rm -rf /usr/share/nginx/html/*

EXPOSE 80

VOLUME /usr/share/nginx/html/

ENTRYPOINT ["/run.sh"]