FROM node:11-alpine
RUN adduser -D -s /bin/sh service-web
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN yarn install
RUN chown -R service-web:service-web /usr/src/app
USER service-web
EXPOSE 3000
CMD ["yarn", "start"]
